### ISSUE TITLE
Error using HB 1.30-57

### ISSUE THREAD

**Issue by johnluber** [aqualinkd/homebridge-aqualinkd#5]
I realize this version of HB is beta but this appears to be related to an underlying change in the way HB handle plug-ins so FYI...

Since upgrading to the beta the logs are filling with:

[2/15/2021, 8:09:30 AM] Received error for the plugin 'homebridge-aqualinkd' from the characteristic 'Model': Error: [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory. Ignoring new value.
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1983:38)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:21)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:631:24)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2119:22)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)

**Comment by sfeakes** [comment]
I'm closing this as it doesn't seem to be a problem in any released version.  Even releases newer than the beta listed above seem to be fine.
